### ISSUE TITLE
Unable to trash a broken symbolic link

### ISSUE THREAD

**Issue by Arkaeriit** [quackduck/rem#4]
When trying to remove a symbolic link that points to nothing, rem fails.
![image](https://user-images.githubusercontent.com/47985708/174311053-32389a4f-a1f2-4750-bf8e-f6b9cf9e2d35.png)
This is due to the facts that the Go function `os.IsNotExists` returns false for that kind of file. I don't know if the bug should be fixed here or if we should notify the developers of Go.

**Comment by quackduck** [comment]
Ooooh that’s such an interesting bug!

We can probably fix this by trying to detect symbolic links, but yeah, the os package should say that the file does exist. I can make an issue if you want.

**Comment by Arkaeriit** [comment]
I tested your fix and it works flawlessly.
