### ISSUE TITLE
Feature: Greater GNU rm compatibility

### ISSUE THREAD

**Issue by Arkaeriit** [quackduck/rem#9]
If we want to use rem as a drop-in replacement for rm in scripts, a greater compatibility with GNU rm might be desirable. PR #8 already takes care of the `-f` flag.

A fist step would be to remove the `-v` flag as a shorthand for `--version` as this flag is more usually used as a shorthand for `--verbose` which result in a wildly different behavior.

Before using rem, I used [trash-cli](https://github.com/andreafrancia/trash-cli) which does the rm compatibility in a pretty smart way. It simply ignores a lot of flag, they are not parsed as a file to trash but they don't have any effect. Should we aim to do the same thing ?

**Comment by quackduck** [comment]
okay, let's do that and then also implement `--`

**Comment by Arkaeriit** [comment]
I am down to do it. By `--`, you mean the flag to indicate that all the following arguments are filenames, don't you?

**Comment by quackduck** [comment]
Yup

**Comment by Arkaeriit** [comment]
As we discussed, adding a `--rm-mode` flag which enable GNU rm compatibility when enabled and disable compatibility when not used would be a better approach.

**Comment by Arkaeriit** [comment]
Since #10 have been merged. We can close the issue.
